[global]
# If false, makes your Streamlit app have a dark theme by default
dataFrameSortColumn = ""

[server]
# List of folders that should not be watched for changes
headless = false
runOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
# Internet address where users should point their browsers in order to connect to the app
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
# The preset Streamlit theme that your custom theme inherits from
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f8ff"
textColor = "#262730"

[client]
# Whether to enable the toolbar
caching = true
displayEnabled = true